/**
 * @fileoverview Data Manager
 * Handles persistent storage of user configurations using a structured JSON file.
 * Automatically initializes and writes state updates asynchronously.
 */
const fs = require('fs');
const path = require('path');

const FILE_PATH = path.join(__dirname, 'users_configs.json');

// Initialize if creating for the first time
if (!fs.existsSync(FILE_PATH)) {
    fs.writeFileSync(FILE_PATH, JSON.stringify({}), 'utf8');
}

/**
 * Reads and parses the configurations directly from the disk.
 * @returns {Object} The complete mapping of chat IDs to arrays of configuration objects.
 */
function readData() {
    try {
        const data = fs.readFileSync(FILE_PATH, 'utf8');
        return JSON.parse(data);
    } catch (e) {
        console.error(`[DataManager] Error reading data: ${e.message}`);
        return {};
    }
}

/**
 * Synchronously overwrites the configurations JSON file with updated data.
 * @param {Object} data - The entire state object to persist.
 */
function writeData(data) {
    try {
        fs.writeFileSync(FILE_PATH, JSON.stringify(data, null, 2), 'utf8');
    } catch (e) {
        console.error(`[DataManager] Error writing data: ${e.message}`);
    }
}

/**
 * Retrieves all saved configurations belonging to a specific user.
 * 
 * @param {string} chatId - The Telegram Chat ID.
 * @returns {Array<Object>} List of configuration objects.
 */
function getUserConfigs(chatId) {
    const data = readData();
    return data[chatId] || [];
}

/**
 * Retrieves a single specific configuration for a user.
 * 
 * @param {string} chatId - The Telegram Chat ID.
 * @param {string} configId - The unique configuration ID.
 * @returns {Object|undefined} The matching configuration object, or undefined.
 */
function getConfig(chatId, configId) {
    const configs = getUserConfigs(chatId);
    return configs.find(c => c.id === configId);
}

/**
 * Saves a new configuration or updates an existing one for a user.
 * Hard limit of 2 configurations per user is enforced here.
 * 
 * @param {string} chatId - The Telegram Chat ID.
 * @param {Object} config - The configuration object. Must contain a unique `.id`.
 * @throws {Error} When attempting to exceed the maximum configuration limit.
 */
function saveUserConfig(chatId, config) {
    const data = readData();
    if (!data[chatId]) {
        data[chatId] = [];
    }

    const existingIndex = data[chatId].findIndex(c => c.id === config.id);
    if (existingIndex >= 0) {
        // Update existing config
        data[chatId][existingIndex] = config;
    } else {
        // Add new config
        if (data[chatId].length >= 2) {
            throw new Error("You have reached the maximum limit of 2 configurations.");
        }
        data[chatId].push(config);
    }
    
    writeData(data);
}

/**
 * Erases a specific configuration object belonging to a user.
 * 
 * @param {string} chatId - The Telegram Chat ID.
 * @param {string} configId - The unique configuration ID generated by `server.js`.
 */
function deleteUserConfig(chatId, configId) {
    const data = readData();
    if (data[chatId]) {
        data[chatId] = data[chatId].filter(c => c.id !== configId);
        writeData(data);
    }
}

module.exports = {
    getUserConfigs,
    getConfig,
    saveUserConfig,
    deleteUserConfig
};
